KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE = yes

EXTRAKEY_ENABLE = yes  # media keys etc.

# Firmware size reduction
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESCAPE_ENABLE = no
MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
