LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no

UNICODE_ENABLE = no
UNICODEMAP_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

